<a href="https://colab.research.google.com/github/Dheeraj024/neural-network-bagging-/blob/main/hyperspectral_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import scipy.io as sio
import matplotlib.pyplot as plt

In [2]:
hyp_data = sio.loadmat("/content/drive/MyDrive/Colab Notebooks/Indian_pines_corrected.mat")
gt_data = sio.loadmat("/content/drive/MyDrive/Colab Notebooks/Indian_pines_gt.mat")

In [3]:
data = hyp_data[sorted(hyp_data.keys())[-1]]

In [4]:
labels = gt_data[sorted(gt_data.keys())[-1]]

In [6]:
print(data.shape)
print(labels.shape)

(145, 145, 200)
(145, 145)


In [8]:
data = data.reshape(data.shape[0]*data.shape[1],data.shape[2])
data

array([[3172, 4142, 4506, ..., 1057, 1020, 1020],
       [2580, 4266, 4502, ..., 1064, 1029, 1020],
       [3687, 4266, 4421, ..., 1061, 1030, 1016],
       ...,
       [3153, 3864, 4282, ..., 1003, 1008, 1000],
       [3155, 4104, 4106, ..., 1011, 1005, 1003],
       [3323, 3860, 4197, ..., 1007, 1004, 1000]], dtype=uint16)

In [9]:
labels = labels.reshape(-1,1)
labels

array([[3],
       [3],
       [3],
       ...,
       [0],
       [0],
       [0]], dtype=uint8)

In [28]:
combine = np.concatenate((data,labels),axis=1)
combine

array([[ 0.6047628 ,  0.21997468,  0.8862633 , ...,  0.38894136,
         1.62910551,  3.        ],
       [-1.06326446,  0.75820528,  0.87074869, ...,  1.17937664,
         1.62910551,  3.        ],
       [ 2.05583381,  0.75820528,  0.55657785, ...,  1.26720278,
         1.06179023,  3.        ],
       ...,
       [ 0.55122814, -0.98670358,  0.01744517, ..., -0.66497235,
        -1.20747086,  0.        ],
       [ 0.55686337,  0.05503305, -0.66519764, ..., -0.92845077,
        -0.7819844 ,  0.        ],
       [ 1.03022246, -1.00406586, -0.31224028, ..., -1.01627691,
        -1.20747086,  0.        ]])

In [29]:
combine = np.delete(combine,np.where(combine[:,-1]==0),axis=0)

In [30]:
combine

array([[ 0.6047628 ,  0.21997468,  0.8862633 , ...,  0.38894136,
         1.62910551,  3.        ],
       [-1.06326446,  0.75820528,  0.87074869, ...,  1.17937664,
         1.62910551,  3.        ],
       [ 2.05583381,  0.75820528,  0.55657785, ...,  1.26720278,
         1.06179023,  3.        ],
       ...,
       [-1.10834627,  0.63666934,  0.04847439, ...,  0.65241979,
         1.34544787, 10.        ],
       [-0.62653435,  0.09843874,  0.06786765, ...,  0.74024593,
         1.34544787, 10.        ],
       [-0.63498719,  0.1331633 ,  0.42858232, ...,  0.74024593,
         0.7781326 , 10.        ]])

In [70]:
hyp_columns = []
for i in range(data.shape[1]):
  hyp_columns.append('b'+str(i))

hyp_columns.append('labels')

In [22]:
df = pd.DataFrame(data,columns = hyp_columns)
df.head()

b0    b1    b2    b3    b4    b5    b6    b7    b8    b9  ...  b190  \
0  3172  4142  4506  4279  4782  5048  5213  5106  5053  4750  ...  1135   
1  2580  4266  4502  4426  4853  5249  5352  5353  5347  5065  ...  1137   
2  3687  4266  4421  4498  5019  5293  5438  5427  5383  5132  ...  1144   
3  2749  4258  4603  4493  4958  5234  5417  5355  5349  5096  ...  1146   
4  2746  4018  4675  4417  4886  5117  5215  5096  5098  4834  ...  1135   

   b191  b192  b193  b194  b195  b196  b197  b198  b199  
0  1094  1090  1112  1090  1062  1069  1057  1020  1020  
1  1108  1104  1117  1091  1079  1085  1064  1029  1020  
2  1111  1114  1114  1100  1065  1092  1061  1030  1016  
3  1122  1108  1109  1109  1071  1088  1060  1030  1006  
4  1110  1107  1112  1094  1072  1087  1052  1034  1019  

[5 rows x 200 columns]

In [23]:
df['labels'] = labels

In [24]:
df.head()

b0    b1    b2    b3    b4    b5    b6    b7    b8    b9  ...  b191  \
0  3172  4142  4506  4279  4782  5048  5213  5106  5053  4750  ...  1094   
1  2580  4266  4502  4426  4853  5249  5352  5353  5347  5065  ...  1108   
2  3687  4266  4421  4498  5019  5293  5438  5427  5383  5132  ...  1111   
3  2749  4258  4603  4493  4958  5234  5417  5355  5349  5096  ...  1122   
4  2746  4018  4675  4417  4886  5117  5215  5096  5098  4834  ...  1110   

   b192  b193  b194  b195  b196  b197  b198  b199  labels  
0  1090  1112  1090  1062  1069  1057  1020  1020       3  
1  1104  1117  1091  1079  1085  1064  1029  1020       3  
2  1114  1114  1100  1065  1092  1061  1030  1016       3  
3  1108  1109  1109  1071  1088  1060  1030  1006       3  
4  1107  1112  1094  1072  1087  1052  1034  1019       3  

[5 rows x 201 columns]

In [25]:
df.describe()

b0            b1            b2            b3            b4  \
count  21025.000000  21025.000000  21025.000000  21025.000000  21025.000000   
mean    2957.363472   4091.321237   4277.502259   4169.956671   4516.678668   
std      354.918708    230.390005    257.827640    280.761254    346.035984   
min     2560.000000   2709.000000   3649.000000   2810.000000   3840.000000   
25%     2602.000000   3889.000000   4066.000000   3954.000000   4214.000000   
50%     2780.000000   4106.000000   4237.000000   4126.000000   4478.000000   
75%     3179.000000   4247.000000   4479.000000   4350.000000   4772.000000   
max     4536.000000   5744.000000   6361.000000   6362.000000   7153.000000   

                 b5            b6            b7            b8            b9  \
count  21025.000000  21025.000000  21025.000000  21025.000000  21025.000000   
mean    4790.595149   4848.317574   4714.732509   4668.904828   4439.065541   
std      414.382138    469.247667    491.728349    533.232855    539.908195   
min     4056.000000   4004.000000   3865.000000   3775.000000   2792.000000   
25%     4425.000000   4421.000000   4263.000000   4173.000000   3940.000000   
50%     4754.000000   4808.000000   4666.000000   4632.000000   4404.000000   
75%     5093.000000   5198.000000   5100.000000   5084.000000   4860.000000   
max     7980.000000   8284.000000   8128.000000   8194.000000   7928.000000   

       ...          b191          b192          b193          b194  \
count  ...  21025.000000  21025.000000  21025.000000  21025.000000   
mean   ...   1061.927848   1060.210273   1063.276813   1050.048514   
std    ...     38.843805     38.712195     41.920969     34.242725   
min    ...    998.000000    999.000000    999.000000    993.000000   
25%    ...   1026.000000   1024.000000   1024.000000   1019.000000   
50%    ...   1053.000000   1052.000000   1054.000000   1043.000000   
75%    ...   1099.000000   1098.000000   1104.000000   1083.000000   
max    ...   1287.000000   1289.000000   1315.000000   1258.000000   

               b195          b196          b197          b198          b199  \
count  21025.000000  21025.000000  21025.000000  21025.000000  21025.000000   
mean    1040.201141   1043.370321   1030.194816   1015.571463   1008.513579   
std       26.452672     29.794418     20.865106     11.386402      7.050921   
min      990.000000    992.000000    989.000000    986.000000    981.000000   
25%     1016.000000   1016.000000   1012.000000   1006.000000   1004.000000   
50%     1033.000000   1035.000000   1026.000000   1014.000000   1009.000000   
75%     1066.000000   1072.000000   1050.000000   1024.000000   1014.000000   
max     1201.000000   1245.000000   1167.000000   1076.000000   1036.000000   

             labels  
count  21025.000000  
mean       4.224923  
std        5.281972  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%       10.000000  
max       16.000000  

[8 rows x 201 columns]

In [26]:
class StandardScaler:
    def __init__(self):
        self.mean = None
        self.std = None
    
    def fit(self, X):
        self.mean = np.mean(X, axis=0)
        self.std = np.std(X, axis=0)
    
    def transform(self, X):
        X_scaled = (X - self.mean) / self.std
        return X_scaled
    
    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

In [27]:
scaler = StandardScaler()
scaler.fit(data)
scaler.transform(data)
data= scaler.fit_transform(data)

In [33]:
df = pd.DataFrame(combine,columns = hyp_columns)
df.head()

b0        b1        b2        b3        b4        b5        b6  \
0  0.604763  0.219975  0.886263  0.388394  0.766763  0.621192  0.777183   
1 -1.063264  0.758205  0.870749  0.911983  0.971949  1.106263  1.073408   
2  2.055834  0.758205  0.556578  1.168434  1.451679  1.212448  1.256685   
3 -0.587088  0.723481  1.262493  1.150625  1.275393  1.070064  1.211931   
4 -0.595541 -0.318256  1.541756  0.879926  1.067317  0.787709  0.781445   

         b7        b8        b9  ...      b191      b192      b193      b194  \
0  0.795717  0.720331  0.575916  ...  0.825689  0.769536  1.162291  1.166742   
1  1.298039  1.271698  1.159363  ...  1.186116  1.131188  1.281565  1.195946   
2  1.448532  1.339213  1.283461  ...  1.263350  1.389511  1.210000  1.458782   
3  1.302107  1.275449  1.216781  ...  1.546542  1.234517  1.090726  1.721618   
4  0.775380  0.804724  0.731502  ...  1.237605  1.208685  1.162291  1.283558   

       b195      b196      b197      b198      b199  labels  
0  0.824090  0.860238  1.284720  0.388941  1.629106     3.0  
1  1.466762  1.397264  1.620216  1.179377  1.629106     3.0  
2  0.937503  1.632213  1.476432  1.267203  1.061790     3.0  
3  1.164328  1.497956  1.428504  1.267203 -0.356498     3.0  
4  1.202132  1.464392  1.045080  1.618507  1.487277     3.0  

[5 rows x 201 columns]

In [34]:
 hyp_columns = hyp_columns[-1:] + hyp_columns[:-1]
 df = df[hyp_columns]
 df.head()

labels        b0        b1        b2        b3        b4        b5  \
0     3.0  0.604763  0.219975  0.886263  0.388394  0.766763  0.621192   
1     3.0 -1.063264  0.758205  0.870749  0.911983  0.971949  1.106263   
2     3.0  2.055834  0.758205  0.556578  1.168434  1.451679  1.212448   
3     3.0 -0.587088  0.723481  1.262493  1.150625  1.275393  1.070064   
4     3.0 -0.595541 -0.318256  1.541756  0.879926  1.067317  0.787709   

         b6        b7        b8  ...      b190      b191      b192      b193  \
0  0.777183  0.795717  0.720331  ...  1.115065  0.825689  0.769536  1.162291   
1  1.073408  1.298039  1.271698  ...  1.155111  1.186116  1.131188  1.281565   
2  1.256685  1.448532  1.339213  ...  1.295271  1.263350  1.389511  1.210000   
3  1.211931  1.302107  1.275449  ...  1.335317  1.546542  1.234517  1.090726   
4  0.781445  0.775380  0.804724  ...  1.115065  1.237605  1.208685  1.162291   

       b194      b195      b196      b197      b198      b199  
0  1.166742  0.824090  0.860238  1.284720  0.388941  1.629106  
1  1.195946  1.466762  1.397264  1.620216  1.179377  1.629106  
2  1.458782  0.937503  1.632213  1.476432  1.267203  1.061790  
3  1.721618  1.164328  1.497956  1.428504  1.267203 -0.356498  
4  1.283558  1.202132  1.464392  1.045080  1.618507  1.487277  

[5 rows x 201 columns]

In [60]:
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights and biases
        self.W1 = np.random.randn(self.input_size, self.hidden_size) * 0.01
        self.b1 = np.zeros((1, self.hidden_size))
        self.W2 = np.random.randn(self.hidden_size, self.output_size) * 0.01
        self.b2 = np.zeros((1, self.output_size))

    def forward(self, X):
        # Forward pass
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = np.maximum(0, self.z1)  # ReLU activation
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = np.exp(self.z2 - np.max(self.z2, axis=1, keepdims=True))  # Softmax activation
        self.a2 /= np.sum(self.a2, axis=1, keepdims=True)
        return self.a2

    def backward(self, X, y, learning_rate):
        # Backward pass
        m = X.shape[0]

        dZ2 = self.a2
        dZ2[range(m), y.astype(int)] -= 1
        dZ2 /= m

        dW2 = np.dot(self.a1.T, dZ2)
        db2 = np.sum(dZ2, axis=0)

        dA1 = np.dot(dZ2, self.W2.T)
        dZ1 = dA1 * (self.a1 > 0)  # ReLU derivative

        dW1 = np.dot(X.T, dZ1)
        db1 = np.sum(dZ1, axis=0)

        # Update weights and biases
        self.W2 -= learning_rate * dW2
        self.b2 -= learning_rate * db2
        self.W1 -= learning_rate * dW1
        self.b1 -= learning_rate * db1

    def train(self, X, y, epochs, learning_rate):
        epsilon = 1e-8
        for epoch in range(epochs):
            # Forward pass
            a2 = self.forward(X)

            # Compute loss
            loss = -np.sum(np.log(a2[range(X.shape[0]), y.astype(int)]+epsilon)) / X.shape[0]

            # Backward pass
            self.backward(X, y, learning_rate)

            # Print loss
            if (epoch+1) % 100 == 0:
              print(f'Epoch {epoch}, Loss: {loss:.4f}')

    def predict(self, X):
        # Predict class labels
        a2 = self.forward(X)
        y_pred = np.argmax(a2, axis=1)
        return y_pred


In [36]:
def sampling(tdata,val):
    len1= int(len(tdata)*val)
    t1 = tdata.sample(frac=1)
    val_data = t1.iloc[0:len1,:]
    train = t1.iloc[len1:,:]
    return val_data,train

In [37]:
# x_train = df.iloc[:,1:]
# y_train = df.iloc[:,0]
# x_test = df.iloc[:,1:]
# y_test = df.iloc[:,0]

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( df.iloc[:,1:] , df.iloc[:,0] , test_size=0.33, random_state=42)

In [42]:
print(x_train)
x_train.shape

             b0        b1        b2        b3        b4        b5        b6  \
0      0.604763  0.219975  0.886263  0.388394  0.766763  0.621192  0.777183   
1     -1.063264  0.758205  0.870749  0.911983  0.971949  1.106263  1.073408   
2      2.055834  0.758205  0.556578  1.168434  1.451679  1.212448  1.256685   
3     -0.587088  0.723481  1.262493  1.150625  1.275393  1.070064  1.211931   
4     -0.595541 -0.318256  1.541756  0.879926  1.067317  0.787709  0.781445   
...         ...       ...       ...       ...       ...       ...       ...   
10244 -0.634987  0.654032 -0.638047 -0.445074 -0.019301  0.049243 -0.077397   
10245 -1.116799  0.654032  0.048474  0.302910  0.009598  0.179560  0.148502   
10246 -1.108346  0.636669  0.048474  0.046458  0.339052  0.309878  0.504399   
10247 -0.626534  0.098439  0.067868  0.078515  0.365061  0.440196  0.434072   
10248 -0.634987  0.133163  0.428582  0.587856  0.628046  0.546380  0.585382   

             b7        b8        b9  ...      b190 

(10249, 200)

In [61]:
nn = NeuralNetwork(X_train.shape[1],128,17)

In [62]:
nn.train(X_test,y_test,30,0.01)

In [64]:
model_net = []
for i in range(5):
    validation,train_data = sampling(df,0.2)
    v_data = validation.iloc[:,1:]
    v_label = validation.iloc[:,0]
    # gen = generator(train_data,8)
    # x,y = gen
    x_data = train_data.iloc[:,1:]
    y_data = train_data.iloc[:,0]
    nn = NeuralNetwork(X_train.shape[1],128,17)
    nn.train(x_data,y_data,50,0.001)
    model_net.append(nn)

In [65]:
y_pred = []
label_op = []
for i in range(len(X_test)):
  input = X_test.iloc[i]
  for model in model_net:
      prediction = model.predict(input)
      label_op.append(prediction)
  max = 0
  res = label_op[0]
  for i in label_op:
      freq = label_op.count(i)
      if freq > max:
          max = freq
          res = i
  label_op.clear()
  y_pred.append(res)      
print(y_pred)

[array([14]), array([11]), array([11]), array([11]), array([12]), array([12]), array([11]), array([11]), array([11]), array([12]), array([11]), array([11]), array([11]), array([14]), array([12]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([14]), array([14]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([11]), array([2]), array([11]), array([14]), array([11]), array([11]), array([11]), array([12]), array([11]), array([14]), array([11]), array([2]), array([11]), array([11]), array([11]), array([11]), array([14]), array([14]), array([14]), array([11]), array([6]), array([14]), array([11]), array([11]), array([11]), array([11]), array([14]), array([11]), array([11]), array([11]), array([11]), array([11]), array([14]), array([11]), array([14]), array([14]), array([14]), a

In [66]:
y_test

9530     14.0
10213    10.0
7434     11.0
3059     11.0
1145     14.0
         ... 
3509     11.0
8740     14.0
1108     12.0
8864     14.0
5461      6.0
Name: labels, Length: 3383, dtype: float64

In [67]:
from sklearn.metrics import accuracy_score
cm = accuracy_score(y_test,y_pred)
print(cm)

0.3056458764410287


In [68]:
old_data = hyp_data[sorted(hyp_data.keys())[-1]]
old_data = old_data.reshape(old_data.shape[0]*old_data.shape[1],old_data.shape[2])
scaler = StandardScaler()
scaler.fit(old_data)
scaler.transform(old_data)
old_data= scaler.fit_transform(old_data)

In [69]:
old_data

array([[ 0.6047628 ,  0.21997468,  0.8862633 , ...,  1.28472014,
         0.38894136,  1.62910551],
       [-1.06326446,  0.75820528,  0.87074869, ...,  1.62021647,
         1.17937664,  1.62910551],
       [ 2.05583381,  0.75820528,  0.55657785, ...,  1.47643233,
         1.26720278,  1.06179023],
       ...,
       [ 0.55122814, -0.98670358,  0.01744517, ..., -1.30339441,
        -0.66497235, -1.20747086],
       [ 0.55686337,  0.05503305, -0.66519764, ..., -0.91997003,
        -0.92845077, -0.7819844 ],
       [ 1.03022246, -1.00406586, -0.31224028, ..., -1.11168222,
        -1.01627691, -1.20747086]])

In [71]:
new_combine =  np.concatenate((data,labels),axis=1)
df_new = pd.DataFrame(new_combine,columns = hyp_columns)

In [72]:
df_new.head()

b0        b1        b2        b3        b4        b5        b6  \
0  0.604763  0.219975  0.886263  0.388394  0.766763  0.621192  0.777183   
1 -1.063264  0.758205  0.870749  0.911983  0.971949  1.106263  1.073408   
2  2.055834  0.758205  0.556578  1.168434  1.451679  1.212448  1.256685   
3 -0.587088  0.723481  1.262493  1.150625  1.275393  1.070064  1.211931   
4 -0.595541 -0.318256  1.541756  0.879926  1.067317  0.787709  0.781445   

         b7        b8        b9  ...      b191      b192      b193      b194  \
0  0.795717  0.720331  0.575916  ...  0.825689  0.769536  1.162291  1.166742   
1  1.298039  1.271698  1.159363  ...  1.186116  1.131188  1.281565  1.195946   
2  1.448532  1.339213  1.283461  ...  1.263350  1.389511  1.210000  1.458782   
3  1.302107  1.275449  1.216781  ...  1.546542  1.234517  1.090726  1.721618   
4  0.775380  0.804724  0.731502  ...  1.237605  1.208685  1.162291  1.283558   

       b195      b196      b197      b198      b199  labels  
0  0.824090  0.860238  1.284720  0.388941  1.629106     3.0  
1  1.466762  1.397264  1.620216  1.179377  1.629106     3.0  
2  0.937503  1.632213  1.476432  1.267203  1.061790     3.0  
3  1.164328  1.497956  1.428504  1.267203 -0.356498     3.0  
4  1.202132  1.464392  1.045080  1.618507  1.487277     3.0  

[5 rows x 201 columns]

In [73]:
 hyp_columns = hyp_columns[-1:] + hyp_columns[:-1]
 df_new = df_new[hyp_columns]
 df_new.head()

labels        b0        b1        b2        b3        b4        b5  \
0     3.0  0.604763  0.219975  0.886263  0.388394  0.766763  0.621192   
1     3.0 -1.063264  0.758205  0.870749  0.911983  0.971949  1.106263   
2     3.0  2.055834  0.758205  0.556578  1.168434  1.451679  1.212448   
3     3.0 -0.587088  0.723481  1.262493  1.150625  1.275393  1.070064   
4     3.0 -0.595541 -0.318256  1.541756  0.879926  1.067317  0.787709   

         b6        b7        b8  ...      b190      b191      b192      b193  \
0  0.777183  0.795717  0.720331  ...  1.115065  0.825689  0.769536  1.162291   
1  1.073408  1.298039  1.271698  ...  1.155111  1.186116  1.131188  1.281565   
2  1.256685  1.448532  1.339213  ...  1.295271  1.263350  1.389511  1.210000   
3  1.211931  1.302107  1.275449  ...  1.335317  1.546542  1.234517  1.090726   
4  0.781445  0.775380  0.804724  ...  1.115065  1.237605  1.208685  1.162291   

       b194      b195      b196      b197      b198      b199  
0  1.166742  0.824090  0.860238  1.284720  0.388941  1.629106  
1  1.195946  1.466762  1.397264  1.620216  1.179377  1.629106  
2  1.458782  0.937503  1.632213  1.476432  1.267203  1.061790  
3  1.721618  1.164328  1.497956  1.428504  1.267203 -0.356498  
4  1.283558  1.202132  1.464392  1.045080  1.618507  1.487277  

[5 rows x 201 columns]

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( df_new.iloc[:,1:] , df_new.iloc[:,0] , test_size=0.3, random_state=42)

nn_new = NeuralNetwork(X_train.shape[1],128,17)
nn_new.train(X_test,y_test,30,0.01)

model_net = []
for i in range(5):
    validation,train_data = sampling(df,0.2)
    v_data = validation.iloc[:,1:]
    v_label = validation.iloc[:,0]
    # gen = generator(train_data,8)
    # x,y = gen
    x_data = train_data.iloc[:,1:]
    y_data = train_data.iloc[:,0]
    nn = NeuralNetwork(X_train.shape[1],128,17)
    nn.train(x_data,y_data,200,0.01)
    model_net.append(nn)

Epoch 99, Loss: 2.0070
Epoch 199, Loss: 1.7499
Epoch 99, Loss: 2.0128
Epoch 199, Loss: 1.7485
Epoch 99, Loss: 2.0106
Epoch 199, Loss: 1.7562
Epoch 99, Loss: 1.9702
Epoch 199, Loss: 1.7393
Epoch 99, Loss: 2.0053
Epoch 199, Loss: 1.7498


In [78]:
y_pred = []
label_op = []
for i in range(len(X_test)):
  input = X_test.iloc[i]
  for model in model_net:
      prediction = model.predict(input)
      label_op.append(prediction)
  max = 0
  res = label_op[0]
  for i in label_op:
      freq = label_op.count(i)
      if freq > max:
          max = freq
          res = i
  label_op.clear()
  y_pred.append(res)      
# print(y_pred)

cm1 = accuracy_score(y_test,y_pred)
print(cm1)

0.17739378566899175
